name: Update Radar Chart
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggering

jobs:
  update_radar_url:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch and Create HTML
        env:
          AIRTABLE_PAT: ${{ secrets.AIRTABLE_PAT }}
        run: |
          # Fetch data from Airtable
          curl -sSL \
            -H "Authorization: Bearer $AIRTABLE_PAT" \
            "https://api.airtable.com/v0/appZEmpmx9gs4yATK/Algorithm5_holdings?fields[]=Combined%20Radar%20URL" \
            -o radarRaw.json
          # Extract the URL from the JSON response
          FETCHED_URL=$(jq -r '.records[] | select(.fields."Combined Radar URL" != null) | .fields."Combined Radar URL"' radarRaw.json | head -n 1)
          echo "Fetched URL: $FETCHED_URL"
          # Create the HTML file with the fetched URL and custom CSS
          cat <<EOF > radar_chart.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Interactive Radar Chart</title>
            <style>
              iframe {
                width: 1600px;
                height: 1170px;  # Adjusted to clip the grey footer
                overflow: hidden;
              }
            </style>
          </head>
          <body>
            <iframe src="$FETCHED_URL" frameborder="0"></iframe>
          </body>
          </html>
          EOF
          # Log the HTML content for verification
          echo "HTML content:"
          cat radar_chart.html

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add radar_chart.html
          git commit -m "Update radar_chart.html with latest URL" || true
          git push
