name: Update Radar Chart
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggering

jobs:
  update_radar_url:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch Radar URL and Create HTML
        env:
          AIRTABLE_PAT: ${{ secrets.AIRTABLE_PAT }}
        run: |
          # 1. Fetch the Combined Radar URL field from Airtable
          curl -sSL \
            -H "Authorization: Bearer $AIRTABLE_PAT" \
            "https://api.airtable.com/v0/appZEmpmx9gs4yATK/Algorithm5_holdings?fields[]=Combined%20Radar%20URL" \
            -o radarRaw.json

          # 2. Extract the first non-null URL
          FETCHED_URL=$(jq -r \
            '.records[]
             | select(.fields."Combined Radar URL" != null)
             | .fields."Combined Radar URL"' radarRaw.json \
            | head -n 1)
          echo "Fetched URL: $FETCHED_URL"

          # 3. Append responsive=false
          EMBED_URL="${FETCHED_URL}&responsive=false"
          echo "Embed URL: $EMBED_URL"

          # 4. Define your logo URL (small version)
          LOGO_URL="https://cdn.cmsfly.com/66cdf8de421f9b001276b539/images/KopievanZondertitel-BYmVe.png"

          # 5. Generate radar_chart.html with header flex containing title + tiny logo
          cat <<EOF > radar_chart.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Interactive Radar Chart</title>
            <style>
              body {
                margin: 0;
                padding: 0;
                display: flex;
                flex-direction: column;
                align-items: center;
                font-family: Arial, sans-serif;
              }
              .header {
                display: flex;
                justify-content: space-between;
                align-items: center;
                width: 380px;
                margin-top: -40px;
              }
              .header img {
                width: 40px;
                height: auto;
              }
              #chart-container {
                width: 380px;
                height: 600px;
              }
              iframe {
                width: 100%;
                height: 100%;
                border: none;
              }
            </style>
          </head>
          <body>
            <div class="header">
              <img src="$LOGO_URL" alt="Logo"/>
            </div>
            <div id="chart-container">
              <iframe
                src="$EMBED_URL"
                allowfullscreen>
              </iframe>
            </div>
          </body>
          </html>
          EOF

          # 6. (Optional) inspect the generated HTML
          echo "---- radar_chart.html ----"
          cat radar_chart.html

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add radar_chart.html
          git commit -m "Update radar_chart.html with header logo" || true
          git push
