name: Update Ticker Data

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch quotes from Tiingo
        env:
          TIINGO_API_KEY: ${{ secrets.TIINGO_API_KEY }}
        run: |
          # Either use -L or the slash in the URL
          curl -sSL "https://api.tiingo.com/iex?tickers=AAPL,TSLA,MSFT,AMZN,GOOGL&token=${TIINGO_API_KEY}" > raw.json
          # Or: curl -sS "https://api.tiingo.com/iex/?tickers=..." > raw.json

          echo "===== raw.json ====="
          cat raw.json

          # Example jq transform (optional):
          cat raw.json \
            | jq 'map(. + {price: (if .last == null then .tngoLast else .last end)})' \
            > data.json

          echo "===== data.json ====="
          cat data.json

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update quotes" || exit 0
          git push origin HEAD:main
