<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!-- Ensure the viewport is set for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ranking Widget</title>
  <style>
    html, body {
      margin: 0;
      padding: 0;
      overflow: hidden; /* Prevent scrollbars on the page */
      font-family: sans-serif;
      -webkit-text-size-adjust: 100%;
      text-size-adjust: 100%;
    }
    #ticker-container {
      width: 100%;
      height: 40px;                /* Set an explicit height */
      overflow-x: hidden;
      white-space: nowrap;
      border: 1px solid #ccc;
      -ms-overflow-style: none;    /* IE and Edge */
      scrollbar-width: none;       /* Firefox */
      -webkit-transform: translate3d(0,0,0); /* Force hardware acceleration */
    }
    /* Hide scrollbar for Chrome, Safari and Opera */
    #ticker-container::-webkit-scrollbar {
      display: none;
    }
    #ticker-link {
      text-decoration: none;
      color: inherit;
      display: block;
    }
    #ticker-text {
      display: inline-block;
      padding-left: 100%;
      animation: none; /* Start with no animation */
      font-size: 16px;
      line-height: 40px;
      will-change: transform;
      -webkit-transform: translateZ(0); /* Force GPU acceleration */
      backface-visibility: hidden;
      opacity: 0.99;
    }
    @keyframes scroll-left {
      0%   { transform: translate(0, 0); }
      100% { transform: translate(-100%, 0); }
    }
    .up   { color: green; }
    .down { color: red; }
    img.logo {
      height: 20px;
      width: auto;
      vertical-align: middle;
      margin-right: 5px;
    }
  </style>
</head>
<body>
  <div id="ticker-container">
    <a id="ticker-link" href="https://victorphilip.com/Rankings" target="_top">
      <div id="ticker-text">Loading final holdings...</div>
    </a>
  </div>

  <script>
    // Set animation delay for continuity
    const duration = 120; // seconds
    const now = Date.now() / 1000;
    const delay = -(now % duration);
    document.getElementById('ticker-text').style.animationDelay = delay + 's';

    // Add a touchstart listener to force a reflow on iOS devices.
    document.addEventListener("touchstart", function() {
      const tickerText = document.getElementById('ticker-text');
      tickerText.style.animation = 'none';
      // Force reflow
      void tickerText.offsetHeight;
      tickerText.style.animation = '';
    }, {passive: true});

    fetch("data.json")
      .then(resp => resp.json())
      .then(finalHoldings => {
        const mapTicker = h => {
          const pct = h.prevClose ? ((h.absReturn / h.prevClose) * 100) : 0;
          const sign = (h.absReturn >= 0) ? "+" : "";
          const retClass = (h.absReturn > 0) ? "up" : (h.absReturn < 0) ? "down" : "";
          const absRet = `${sign}${parseFloat(h.absReturn).toFixed(1)}`;
          const pctStr = `${sign}${parseFloat(pct).toFixed(1)}%`;
          const priceStr = parseFloat(h.price).toFixed(2);
          const logoHtml = h.logo ? `<img class="logo" src="${h.logo}" alt="${h.baseTicker} logo">` : "";
          
          return `
            <span class="ticker-item">
              ${logoHtml}
              ${h.baseTicker} $${priceStr} 
              <span class="${retClass}">${absRet}</span> 
              <span class="${retClass}">(${pctStr})</span>
            </span>
          `;
        };

        const items = finalHoldings.map(mapTicker).join(" | ");
        const tickerText = document.getElementById('ticker-text');
        tickerText.innerHTML = items;

        // Force a reflow to help trigger the animation on iOS
        tickerText.offsetHeight;

        // Start the animation after setting content
        setTimeout(() => {
          tickerText.style.animation = `scroll-left 120s linear infinite`;
        }, 100);
      })
      .catch(err => {
        console.error("Error loading final holdings:", err);
        document.getElementById('ticker-text').textContent = "Error loading final holdings.";
      });
  </script>
</body>
</html>
